server {
    listen 8080;
    server_name localhost;

    # Nén gzip để tăng tốc độ tải trang
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Hỗ trợ React Router (client-side routing)
        try_files $uri $uri/ /index.html;
    }

    # Bỏ qua logs cho các request favicon
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
